### ISSUE TITLE
Why did you unstar my repos

### ISSUE THREAD

**Issue by JavaCode7** [nguyenphuminh/nguyenphuminh#1]
I understand that this is a bit childish to ask but i do not understand why you have unstarred my ```Thulium``` and ```Caesium``` repositories.

**Comment by nguyenphuminh** [comment]
Oh, I’m very sorry about that, that might be my mistake since I’m unstaring several repos. I will star them again, those are great languages btw <3

**Comment by JavaCode7** [comment]
Thanks @nguyenphuminh Hey, would you like to join Technetium Inc.?
